services:
  app:
    build: .
    container_name: springboot-redis-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - redis-net

  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - redis-net

networks:
  redis-net:
